{% set name = "daops" %}
{% set version = "0.13.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/daops-{{ version }}.tar.gz
  sha256: 3bbee5d081f3abf8682187aa9287f25e9963024ed7ec10030d4e644b5ca1f139

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - flit-core >=3.9,<4.0
    - pip
  run:
    - python >={{ python_min }}
    - clisops >=0.12.1,<0.15.0
    - dask >=2.6.0
    - elasticsearch >=7.9.1
    - cftime >=1.4.1
    - netcdf4 >=1.4
    - numba
    - numpy >=1.16
    - roocs-utils >=0.6.4
    - roocs-grids >=0.1.2
    - sparse >=0.8.0
    - xarray >=0.21,<2023.3.0 # https://github.com/pydata/xarray/issues/7794
    - xesmf >=0.8.2
    - intake >=0.7.0,<2.0
    - loguru >=0.5.3
    - fsspec
    - aiohttp
    - zarr ==2.13.3
    - zstandard


test:
  imports:
    - daops
    - daops.data_utils
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/roocs/daops
  summary: daops - data-aware operations
  license: BSD-3-Clause
  license_file: LICENSE

  description: |
    The daops library (pronounced "day-ops") provides a python interface to a
    set of operations suitable for working with climate simulation outputs.
    It is typically used with ESGF data sets that are described in NetCDF files.
    daops is unique in that it accesses a store of fixes defined for data sets
    that are irregular when compared with others in their population.

extra:
  recipe-maintainers:
    - ellesmith88
    - cehbrecht
