{% set name = "daops" %}
{% set version = "0.11.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/daops-{{ version }}.tar.gz
  sha256: 3b72c953b1b51641ff142339b7703b45bf9cc1276f0a2e19086ae9e4f58146a7

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
    - pytest-runner
  run:
    - python >=3.9
    - clisops >=0.12.0
    - dask >=2.6.0
    - elasticsearch >=7.9.1
    - cftime >=1.4.1
    - netcdf4 >=1.4
    - numba
    - numpy >=1.16
    - roocs-utils >=0.6.2
    - roocs-grids >=0.1.2
    - sparse >=0.8.0
    - xarray >=0.21,<2023.3.0 # https://github.com/pydata/xarray/issues/7794
    - xesmf >=0.8.2
    - intake
    - fsspec
    - aiohttp
    - loguru >=0.5.3


test:
  imports:
    - daops
    - daops.data_utils
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/roocs/daops
  summary: daops - data-aware operations
  license: BSD-3-Clause
  license_file: LICENSE

  description: |
    The daops library (pronounced "day-ops") provides a python interface to a
    set of operations suitable for working with climate simulation outputs.
    It is typically used with ESGF data sets that are described in NetCDF files.
    daops is unique in that it accesses a store of fixes defined for data sets
    that are irregular when compared with others in their population.

extra:
  recipe-maintainers:
    - ellesmith88
    - cehbrecht
