{% set name = "daops" %}
{% set version = "0.8.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/daops-{{ version }}.tar.gz
  sha256: c1586dcd248c242e48bb0c21cf339ebea952d997f5abd75d57df2c9ac106aad1

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
    - pytest-runner
  run:
    - python >=3.7
    - clisops >=0.9.0
    - dask >=2.6.0
    - elasticsearch >=7.9.1
    - cftime >=1.4.1
    - netcdf4 >=1.4
    - numpy >=1.16
    - roocs-utils >=0.5.0
    - xarray >=0.15
    - intake
    - fsspec
    - aiohttp
    - loguru >=0.5.3


test:
  imports:
    - daops
    - daops.data_utils
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/roocs/daops
  summary: daops - data-aware operations
  license: BSD-3-Clause
  license_file: LICENSE

  description: |
    The daops library (pronounced "day-ops") provides a python interface to a
    set of operations suitable for working with climate simulation outputs.
    It is typically used with ESGF data sets that are described in NetCDF files.
    daops is unique in that it accesses a store of fixes defined for data sets
    that are irregular when compared with others in their population.

extra:
  recipe-maintainers:
    - ellesmith88
    - cehbrecht
